//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doctor_fonder.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class doctor_finderEntities3 : DbContext
    {
        public doctor_finderEntities3()
            : base("name=doctor_finderEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<appoitment> appoitments { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<degree> degrees { get; set; }
        public virtual DbSet<doctor> doctors { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<specility> specilities { get; set; }
        public virtual DbSet<state> states { get; set; }
    }
}
